[package]
name = "topohedral-integrate"
version = "0.1.0"
edition = "2021"

[features]
enable_trace = ["topohedral-tracing/enable_trace"]

[dependencies]
nalgebra = "0.32.6"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
approx = "0.5.1"
log = "0.4.21"
topohedral-tracing = {path = "../topohedral-tracing"}

[dev-dependencies]
ctor = "0.2.8"
