[graph]
all-features = true

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
    "sparse+https://cargo.cloudsmith.io/topohedrallabs/topohedral/",
]
